"""initial

Revision ID: 911d6a05f6e5
Revises: aa135a729111
Create Date: 2025-03-19 18:18:56.175809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911d6a05f6e5'
down_revision: Union[str, None] = 'aa135a729111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('patient_code', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('reg_year', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket_name', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=50), nullable=False),
    sa.Column('extension', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('mail_address', sa.String(length=50), nullable=False),
    sa.Column('inn', sa.String(length=10), nullable=False),
    sa.Column('kpp', sa.String(length=9), nullable=False),
    sa.Column('bik', sa.String(length=9), nullable=False),
    sa.Column('ogrn', sa.String(length=13), nullable=False),
    sa.Column('okved_code', sa.String(length=7), nullable=False),
    sa.Column('all_okved_code', sa.String(length=50), nullable=False),
    sa.Column('director_name', sa.String(length=50), nullable=False),
    sa.Column('chief_accountant_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('tel', sa.String(length=50), nullable=False),
    sa.Column('settlement_account', sa.String(length=50), nullable=False),
    sa.Column('corr_account', sa.String(length=20), nullable=False),
    sa.Column('logo_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('site_link', sa.String(length=100), nullable=False),
    sa.Column('okved_approved', sa.Boolean(), nullable=False),
    sa.Column('land_hectares', sa.Float(), nullable=False),
    sa.Column('land_status_ok', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['logo_id'], ['media_files.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corr_account'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('settlement_account'),
    sa.UniqueConstraint('site_link'),
    sa.UniqueConstraint('tel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization')
    op.drop_table('regions')
    op.drop_table('media_files')
    op.drop_table('breeds')
    # ### end Alembic commands ###
