"""init

Revision ID: ecd01c564b8f
Revises: 
Create Date: 2025-05-14 22:06:01.477891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd01c564b8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('patient_code', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('usage_direction', sa.Enum('riding', 'productive', 'decorative', 'duty', 'hard_duty', 'universal', name='usagedirection'), nullable=False),
    sa.Column('reg_year', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cringe', sa.String(length=50), nullable=False),
    sa.Column('faust', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket_name', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=50), nullable=False),
    sa.Column('extension', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('accounts_all', sa.Boolean(), nullable=False),
    sa.Column('races_full', sa.Boolean(), nullable=False),
    sa.Column('bonitation_full', sa.Boolean(), nullable=False),
    sa.Column('specialist_full', sa.Boolean(), nullable=False),
    sa.Column('files_full', sa.Boolean(), nullable=False),
    sa.Column('hold_horses', sa.Boolean(), nullable=False),
    sa.Column('create_bonitations', sa.Boolean(), nullable=False),
    sa.Column('create_races', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('race_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('commerce', 'traditional', name='racecategorytype'), nullable=True),
    sa.Column('male_allowed', sa.Boolean(), nullable=False),
    sa.Column('female_allowed', sa.Boolean(), nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('jockey_weight_min', sa.Integer(), nullable=True),
    sa.Column('jockey_weight_max', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supportmodels',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('organization_type', sa.Enum('hippodrome', 'breeder', 'reproducer', 'entity', name='organizationtype'), nullable=False),
    sa.Column('given_name', sa.String(length=50), nullable=False),
    sa.Column('family_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('general', 'task', 'none', name='notificationtype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_type', sa.Enum('hippodrome', 'breeder', 'reproducer', 'entity', name='organizationtype'), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('mail_address', sa.String(length=50), nullable=False),
    sa.Column('inn', sa.String(length=10), nullable=False),
    sa.Column('kpp', sa.String(length=9), nullable=False),
    sa.Column('bik', sa.String(length=9), nullable=False),
    sa.Column('ogrn', sa.String(length=13), nullable=False),
    sa.Column('okved_code', sa.String(length=7), nullable=False),
    sa.Column('all_okved_code', sa.String(length=50), nullable=False),
    sa.Column('director_name', sa.String(length=50), nullable=False),
    sa.Column('chief_accountant_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('tel', sa.String(length=50), nullable=False),
    sa.Column('settlement_account', sa.String(length=50), nullable=False),
    sa.Column('corr_account', sa.String(length=20), nullable=False),
    sa.Column('logo_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('not_activated', 'active', 'deleted', name='organizationstatus'), nullable=False),
    sa.Column('site_link', sa.String(length=100), nullable=False),
    sa.Column('okved_approved', sa.Boolean(), nullable=False),
    sa.Column('land_hectares', sa.Float(), nullable=False),
    sa.Column('land_status_ok', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['logo_id'], ['media_files.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corr_account'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('settlement_account'),
    sa.UniqueConstraint('site_link'),
    sa.UniqueConstraint('tel')
    )
    op.create_table('redis_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Uuid(), nullable=False),
    sa.Column('browser', sa.String(length=50), nullable=False),
    sa.Column('os', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.create_table('bonitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('prefers_time_min', sa.DateTime(), nullable=True),
    sa.Column('prefers_time_max', sa.DateTime(), nullable=True),
    sa.Column('approved_time', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('org_contact_name', sa.String(length=50), nullable=False),
    sa.Column('org_contact_tel', sa.String(length=50), nullable=False),
    sa.Column('org_contact_link', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'canceled', name='bonitationstatus'), nullable=True),
    sa.Column('type', sa.Enum('bonitation', 'chipization', name='bonitationtype'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('birth_region_id', sa.Integer(), nullable=False),
    sa.Column('chip_num', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', 'none', name='sex'), nullable=False),
    sa.Column('passport_series', sa.TEXT(), nullable=False),
    sa.Column('passport_number', sa.TEXT(), nullable=False),
    sa.Column('passport_issuer', sa.TEXT(), nullable=False),
    sa.Column('passport_issued_at', sa.DateTime(), nullable=False),
    sa.Column('nickname', sa.TEXT(), nullable=False),
    sa.Column('suit', sa.TEXT(), nullable=False),
    sa.Column('father_id', sa.Integer(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('born_at', sa.DateTime(), nullable=True),
    sa.Column('dead_at', sa.DateTime(), nullable=True),
    sa.Column('life_status', sa.Enum('born', 'foal', 'active', 'grand', 'semen', 'dead', 'none', name='lifestatus'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('oblique_length', sa.Integer(), nullable=True),
    sa.Column('torso_circumference', sa.Integer(), nullable=True),
    sa.Column('pastern_circumference', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('rating_origin', sa.Integer(), nullable=True),
    sa.Column('rating_soundings', sa.Integer(), nullable=True),
    sa.Column('rating_exterior', sa.Integer(), nullable=True),
    sa.Column('rating_offspring', sa.Integer(), nullable=True),
    sa.Column('rating_donorship', sa.Integer(), nullable=True),
    sa.Column('rating_typicality', sa.Integer(), nullable=True),
    sa.Column('rating_breed', sa.Integer(), nullable=True),
    sa.Column('rating_efficiency', sa.Integer(), nullable=True),
    sa.Column('rating_adaptability', sa.Integer(), nullable=True),
    sa.Column('coolness', sa.Integer(), nullable=True),
    sa.Column('insemination_percent', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['birth_region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ),
    sa.ForeignKeyConstraint(['father_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['media_files.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('race_day_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('prize_money', sa.Integer(), nullable=True),
    sa.Column('prize_places', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Enum('rur', 'usd', 'eur', name='currencytype'), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('track_cover', sa.Enum('sand', 'grass', 'other', name='trackcover'), nullable=True),
    sa.Column('track_status', sa.Enum('dry', 'wet', 'other', name='trackstatus'), nullable=True),
    sa.Column('type', sa.Enum('race', 'gallop', name='racetype'), nullable=True),
    sa.Column('with_obstacles', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['race_categories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['race_day_id'], ['race_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('given_name', sa.String(length=50), nullable=False),
    sa.Column('family_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=False),
    sa.Column('qualification', sa.Enum('trainer', 'trainer_assistant', 'jockey', 'jockey_apprentice', 'trainee_traveler', 'jockey_amateur', name='specialistqualification'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('license_expired_at', sa.DateTime(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['media_files.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonitation_horses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bonitation_id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bonitation_id'], ['bonitations.id'], ),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horse_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horses_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('new_value', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_name'),
    sa.UniqueConstraint('new_value')
    )
    op.create_table('horses_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['media_files.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horses_races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Interval(), nullable=True),
    sa.Column('result_place', sa.Integer(), nullable=True),
    sa.Column('start_place', sa.Integer(), nullable=True),
    sa.Column('prize_money', sa.Integer(), nullable=True),
    sa.Column('handicap', sa.Integer(), nullable=True),
    sa.Column('doping_control_ok', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['specialists.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['specialists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialists_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialist_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['media_files.id'], ),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialists_docs')
    op.drop_table('horses_races')
    op.drop_table('horses_photos')
    op.drop_table('horses_history')
    op.drop_table('horse_owners')
    op.drop_table('bonitation_horses')
    op.drop_table('specialists')
    op.drop_table('races')
    op.drop_table('organizations_docs')
    op.drop_table('horses')
    op.drop_table('bonitations')
    op.drop_table('redis_sessions')
    op.drop_table('organizations')
    op.drop_table('notifications')
    op.drop_table('users')
    op.drop_table('supportmodels')
    op.drop_table('race_categories')
    op.drop_table('regions')
    op.drop_table('race_days')
    op.drop_table('permissions')
    op.drop_table('media_files')
    op.drop_table('categories')
    op.drop_table('breeds')
    # ### end Alembic commands ###
